# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics

on:
  # Schedule updates
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}  
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: main
          user: zAlweNy26
          template: classic
          base: header, activity, community, repositories, metadata
          config_order: base.header, base.activity+community, isocalendar, base.repositories, languages, topics
          config_timezone: Europe/Rome
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_ignored: smali
          plugin_notable: yes
          plugin_traffic: yes
          plugin_topics: yes
          plugin_topics_mode: "mastered"
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, languages-graphs
          plugin_wakatime_limit: 5
          plugin_wakatime_languages_ignored: css, yml, yaml, json, svg, md
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "76561198154675159"
          plugin_steam_sections: recently-played
          plugin_steam_achievements_limit: 0
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 1
