# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics

on:
  # Schedule updates
  schedule: 
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}  
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: main
          user: zAlweNy26
          template: classic
          base: header, activity, community, repositories, metadata
          config_order: base.header, base.activity+community, isocalendar, base.repositories, languages, topics
          config_timezone: Europe/Rome
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_ignored: yaml, json, toml
          plugin_notable: yes
          plugin_traffic: yes
          plugin_topics: yes
          plugin_topics_mode: "mastered"
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "76561198154675159"
          plugin_steam_sections: recently-played
          plugin_steam_achievements_limit: 0
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 1
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }}
          SHOW_TITLE: true
          SHOW_TOTAL: true
          SHOW_TIME: true
          LANG_COUNT: 10
          TIME_RANGE: last_30_days
          IGNORED_LANGUAGES: YAML JSON TOML
          BLOCKS: ░▒▓█
          CODE_LANG: bash
          COMMIT_MESSAGE: "Update WakaTime section - [Skip GitHub Action]"
          COMMITTER_NAME: "zAlweNy26"
          COMMITTER_EMAIL: "alwe.dev@gmail.com"
          AUTHOR_NAME: "zAlweNy26"
          AUTHOR_EMAIL: "alwe.dev@gmail.com"
